url: "https://adatomica.com"
baseurl: ""
permalink: pretty

collections:
  people:
    output: false

exclude:
  - Adatomica website redesign/
  - docs/
  - scripts/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
